# @format

# @package tomgrv/actions/setup-node

name: Setup Node.js
description: Shared Node.js and npm setup for PR validation actions.
author: Perspikapps
branding:
  icon: check-circle
  color: blue

inputs:
  cache:
    description: Supported package manager
    required: false
    default: 'npm'
  node-version:
    description: Node.js version to set up. Defaults to version specified in package.json or 24.
    required: false
    default: '24'
  options:
    description: Additional arguments to pass to the install command. includes --no-progress and --workspaces by default.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v6
      id: node-setup
      with:
        cache: ${{ inputs.cache }}
        node-version: ${{ inputs.node-version }}

    - name: Install Node dependencies
      if: ${{ hashFiles('package-lock.json') }}
      shell: sh
      run: npm ci --no-progress --workspaces ${{ inputs.options }}
