# @format

# @package tomgrv/actions/check-security-npm

name: Validate PR Security NPM
description: Run npm dependency security audit and report via reviewdog.
author: Perspikapps
branding:
  icon: check-circle
  color: blue

inputs:
  github-token:
    description: GitHub token for reviewdog reporting.
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error].'
    required: false
    default: error
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-check,github-pr-review].'
    required: false
    default: github-pr-check
  filter-mode:
    description: 'Filtering mode for the reviewdog command [added,diff_context,file,nofilter].'
    required: false
    default: nofilter
  fail-level:
    description: 'Exit code for reviewdog if it finds at least the specified level of diagnostic [none,any,info,warning,error].'
    required: false
    default: none
  reviewdog-flags:
    description: Additional reviewdog flags.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Node toolchain
      uses: $/setup-node

    - name: Setup reviewdog toolchain
      uses: $/setup-reviewdog

    - name: Run npm security audit
      shell: sh
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
        REVIEWDOG_REPORTER: ${{ inputs.reporter }}
        REVIEWDOG_LEVEL: ${{ inputs.level }}
        REVIEWDOG_FILTER_MODE: ${{ inputs.filter-mode }}
        REVIEWDOG_FAIL_LEVEL: ${{ inputs.fail-level }}
        REVIEWDOG_FLAGS: ${{ inputs.reviewdog-flags }}
      run: sh "${{ github.action_path }}/run.sh"
