# @format

name: Test Run Deployer

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'run-deployer/**'
      - '.github/workflows/test-run-deployer.yml'
  pull_request:
    paths:
      - 'run-deployer/**'
      - '.github/workflows/test-run-deployer.yml'

permissions:
  contents: read

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bats
        uses: bats-core/bats-action@4.0.0

      - name: Run bats tests
        run: bats run-deployer/run.bats
