# @format

name: Validate PR Title
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Validate and autocorrect PR title if needed
        uses: tomgrv/actions/check-pr-format@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fix: true
  check-pr-source-branch:
    name: Validate PR source branch
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write
    steps:
      - name: Check PR source branch
        uses: tomgrv/actions/check-pr-source-branch@v3
